// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Read the URL directly instead of using Prisma's `env()` helper. `env()` THROWS
// (PrismaConfigEnvError) the moment the variable is missing, which breaks
// `prisma generate` in any build environment that has no DATABASE_URL — even
// though `generate` never opens a connection. Only commands that actually talk
// to the database (migrate / db push / studio / db seed) need it, and those run
// at runtime (e.g. Liara's `liara_pre_start.sh`), where the variable IS set.
const databaseUrl = process.env.DATABASE_URL ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from here (older versions used the
    // "prisma" field in package.json). Run it with `npx prisma db seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: { url: databaseUrl },
});
